name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v6

      - name: Generate cache key
        run: .github/scripts/checksum.sh checksum.txt

      - uses: actions/cache@v6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Install JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 11
          
      - name: Dependency Guard
        run: ./gradlew dependencyGuard --no-daemon --stacktrace

      - name: Test Plugin
        run: ./gradlew -p dependency-guard clean check apiCheck --no-daemon --stacktrace

      - name: (Fail-only) Bundle test reports
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: (Fail-only) Upload the build report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-report
          path: build-reports.zip

  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'dropbox/dependency-guard' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: [build]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::521590706193:role/oidc-github-dropbox-dependency-guard-branch-main
          aws-region: us-west-2

      - name: Get Maven Central secrets from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v3
        with:
          secret-ids: |
            SONATYPE_USERNAME,sdk-release-maven-central-token-username
            SONATYPE_PASSWORD,sdk-release-maven-central-token-password
            SIGNING_KEY,sdk-release-signing-key
            SIGNING_PASSWORD,sdk-release-signing-password
          parse-json-secrets: false

      - name: Upload Snapshot
        run: ./gradlew -p dependency-guard clean publish --no-daemon --no-parallel --no-configuration-cache --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ env.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ env.SIGNING_PASSWORD }}

      - name: Retrieve Version
        run: echo "VERSION_NAME=$(./gradlew -q -p dependency-guard printVersionName)" >> $GITHUB_ENV

      - name: Publish release (main only)
        run: ./gradlew -p dependency-guard closeAndReleaseRepository --no-daemon --no-parallel
        if: success() && !endsWith(env.VERSION_NAME, '-SNAPSHOT')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.SONATYPE_PASSWORD }}
